molgenis/molgenis-ui-form

- src/components/FormComponent.vue
- src/components/FormFieldComponent.vue
- src/components/field-types/CheckboxFieldComponent.vue
- src/components/field-types/RadioFieldComponent.vue
- src/components/field-types/SingleSelectFieldComponent.vue
- src/components/field-types/TextAreaFieldComponent.vue
- src/components/field-types/TypedFieldComponent.vue
- src/formDemoMockResponse.js
- src/util/EntityToStateMapper.js
- test/e2e/specs/form-interaction-tests.js
- test/unit/karma.conf.js
- test/unit/specs/FormComponent.spec.js
- test/unit/specs/FormFieldComponent.spec.js
- test/unit/specs/field-types/CheckboxFieldComponent.spec.js
- test/unit/specs/field-types/RadioFieldComponent.spec.js
- test/unit/specs/field-types/SingleSelectFieldComponent.spec.js
- test/unit/specs/field-types/TextAreaFieldComponent.spec.js
- test/unit/specs/field-types/TypedFieldComponent.spec.js
**note** code in FormComponent that is not covered by unit-test is covered by an extensive e2e test --> see form-interaction-test.js
> Add the EYE to molgenis-ui-form

- src/components/field-types/MultiSelectFieldComponent.vue
- src/flow.types.js
- src/formDemoMockResponse.js
- src/util/EntityToStateMapper.js
- test/unit/specs/util/EntityToStateMapper.spec.js
- test/unit/specs/util/test-schemas.js
Translate ONE_TO_MANY to a disabled multi-select field
> [Feature] ONE_TO_MANY field

- src/components/field-types/DateFieldComponent.vue
- src/components/field-types/TextAreaFieldComponent.vue
- src/components/field-types/TypedFieldComponent.vue
- test/unit/specs/field-types/TypedFieldComponent.spec.js
Remove 'large' field modifier to have consistent styling
> remove 'large' field modifier to have consistent styling

- index.html
> update bootstrap version

- src/FormDemo.vue
- src/components/FormComponent.vue
- src/components/FormFieldComponent.vue
- src/components/field-types/CheckboxFieldComponent.vue
- src/components/field-types/CodeEditorFieldComponent.vue
- src/components/field-types/DateFieldComponent.vue
- src/components/field-types/FileFieldComponent.vue
- src/components/field-types/MultiSelectFieldComponent.vue
- src/components/field-types/RadioFieldComponent.vue
- src/components/field-types/SingleSelectFieldComponent.vue
- src/components/field-types/TextAreaFieldComponent.vue
- src/components/field-types/TypedFieldComponent.vue
- test/unit/specs/FormComponent.spec.js
- test/unit/specs/FormFieldComponent.spec.js
- test/unit/specs/field-types/CheckboxFieldComponent.spec.js
- test/unit/specs/field-types/CodeEditorComponent.spec.js
- test/unit/specs/field-types/DateFieldComponent.spec.js
- test/unit/specs/field-types/FileFieldComponent.spec.js
- test/unit/specs/field-types/MultiSelectFieldComponent.spec.js
- test/unit/specs/field-types/RadioFieldComponent.spec.js
- test/unit/specs/field-types/SingleSelectFieldComponent.spec.js
- test/unit/specs/field-types/TextAreaFieldComponent.spec.js
- test/unit/specs/field-types/TypedFieldComponent.spec.js
having the form state exposed allows the molgenis-ui-form user to acces the formState 
expose formState as a property
rename state to formState at the form level
rename state to fieldState at the field level
> expose formState as a property

- test/e2e/specs/field-render-tests.js
- test/e2e/specs/form-interaction-tests.js
ie e2e tests are failing on travis, this may be due to slowness
> Allow time for animation and  js slowness on ie

- test/e2e/specs/field-render-tests.js
- test/e2e/specs/form-interaction-tests.js
fix ie11 tests for flatpicker by clicking outside of flatpicker box
https://github.com/chmln/flatpickr/issues/900com/chmln/flatpickr/issues/900)
> click outside of flatpicker as workaround for ie bug 

- README.md
- src/FormDemo.vue
- src/components/FormComponent.vue
- src/components/field-types/CheckboxFieldComponent.vue
- src/components/field-types/CodeEditorFieldComponent.vue
- src/components/field-types/DateFieldComponent.vue
- src/components/field-types/FileFieldComponent.vue
- src/components/field-types/MultiSelectFieldComponent.vue
- src/components/field-types/RadioFieldComponent.vue
- src/components/field-types/SingleSelectFieldComponent.vue
- src/components/field-types/TextAreaFieldComponent.vue
- src/components/field-types/TypedFieldComponent.vue
- src/flow.types.js
- test/unit/specs/FormComponent.spec.js
+ remove hooks ( these are no longer needed when the formData is exposed)
+ update demo
> expose form data to component user

- src/components/FormFieldComponent.vue
fix rename fieldState, otherwise the state does not get passed
> fix rename fieldState, otherwise the state does not get passed

- test/unit/specs/field-types/CheckboxFieldComponent.spec.js
make test assertion independent or array ordering
+
remove unused param
> make test assertion independent or array ordering

- src/components/field-types/RadioFieldComponent.vue
- src/flow.types.js
- src/util/EntityToFormMapper.js
- test/unit/specs/util/EntityToFormMapper.spec.js
Use booleans instead of strings as boolean values + add 'bool' attr in case of booleans for vue-form to handle boolean as a boolean
> Fix boolean bug

- README.md
- config/index.js
- package.json
- src/components/FormFieldMessages.vue
- src/main.js
- yarn.lock
+ update mock response
+ update readme
+ update dev dep for molgenis-i18n-js
> Update forms to work with explicit 'ui-form' namespace

- CHANGELOG.md
> [CHORE] updated changelog for publishing purposes

- Jenkinsfile
Check: https://codecov.io/gh/molgenis/molgenis-ui-form to view results in this commit
- Code reviewed
- Code unit/integration/system tested
- No warnings during install
> [FIX] Updated codecov token to push results to molgenis-ui-form

- CHANGELOG.md
- README.md
- src/flow.types.js
- src/util/EntityToFormMapper.js
- test/unit/specs/util/EntityToFormMapper.spec.js
- test/unit/specs/util/test-schemas.js
if set to true, maps non visible attributes to visible field
defaults to false
- For functional compatibility 'react-froms'
> Add toggle for mapping non visible attributes to visible field

- test/e2e/nightwatch.conf.js
> [CHORE] Added change id for better discovery in saucelabs

- CHANGELOG.md
> Update changelog to prepare for 1.2.0 release

- src/main.js
- src/util/EntityToFormMapper.js
- test/unit/specs/util/EntityToFormMapper.spec.js
- test/unit/specs/util/test-schemas.js
- Parse molgenis date to remove time part
- fix indentation in main.js
> Fix #220 Molgenis alternative data format is seen as invalid

- test/unit/specs/field-types/DateFieldComponent.spec.js
Replace mount with shallow mount to avoid null pointer in subComponent due to insufficient stubbing
> Clean up error in test logging

- src/components/field-types/DateFieldComponent.vue
- src/util/helpers/evaluator.js
- test/unit/specs/util/helpers/evaluator.spec.js
- update age function to handle invalid date string
> Fix 226 Allow clearing of a date /date-time field

- src/example/ExamplePage.vue
- src/example/validation-functions/AgeExample.vue
- src/main.js
- src/util/helpers/evaluator.js
- test/unit/specs/util/helpers/evaluator.spec.js
Replace updated age function with original age function
- add example page for age function
- add unit test for one by one check
> Fix #236 Age function is off by one year for future dates

- Jenkinsfile
> [CHORE] Moved registries to build node and updated build feedback to hubot

- README.md
- src/components/FormFieldComponent.vue
- src/components/field-types/CheckboxFieldComponent.vue
- src/components/field-types/CodeEditorFieldComponent.vue
- src/components/field-types/DateFieldComponent.vue
- src/components/field-types/FileFieldComponent.vue
- src/components/field-types/MultiSelectFieldComponent.vue
- src/components/field-types/RadioFieldComponent.vue
- src/components/field-types/SingleSelectFieldComponent.vue
- src/components/field-types/TextAreaFieldComponent.vue
- src/components/field-types/TypedFieldComponent.vue
- test/e2e/specs/field-render-tests.js
- test/unit/specs/FormFieldComponent.spec.js
- test/unit/specs/field-types/CheckboxFieldComponent.spec.js
- test/unit/specs/field-types/DateFieldComponent.spec.js
- test/unit/specs/field-types/FileFieldComponent.spec.js
- test/unit/specs/field-types/MultiSelectFieldComponent.spec.js
- test/unit/specs/field-types/RadioFieldComponent.spec.js
- test/unit/specs/field-types/SingleSelectFieldComponent.spec.js
- test/unit/specs/field-types/TextAreaFieldComponent.spec.js
> Fire dataChange after validation is finished

- CHANGELOG.md
- config/index.js
- src/example/entity/CreateEntityExample.vue
- src/example/entity/UpdateEntityExample.vue
> [Task] Rename boolean i18n keys to avoid key name collision with molgenis

- CHANGELOG.md
> [CHORE] Changelog version update to 2.0.2

- Jenkinsfile
- test/e2e/specs/field-render-tests.js
> [FIX] E2E Fieldset rendering

- src/components/FormFieldMessages.vue
- test/e2e/specs/integer-field-test.js
- test/e2e/specs/unique-field-test.js
- test/unit/specs/field-types/TypedFieldComponent.spec.js
> fix: Style validation messages

- Jenkinsfile
> [CHORE] inline notifications

- config/index.js
- package.json
- test/e2e/nightwatch.conf.js
- yarn.lock
@connoratrug I think this is now fixed: https://github.com/sagalbot/vue-select/issues/527. However I do not know for sure. Can you check?
> [CHORE] bumped version of vue-select to 2.6.3

- src/formDemoMockResponse.js
- src/util/EntityToFormMapper.js
- test/unit/specs/util/EntityToFormMapper.spec.js
fixes issue #255
show visible auto field in create mode
> fix: Auto generated dates not working

- index.html
- src/components/field-types/RadioFieldComponent.vue
- src/example/ExamplePage.vue
- src/example/radio/RadioExample.vue
- src/main.js
- test/e2e/specs/radio-field-test.js
- test/unit/specs/field-types/RadioFieldComponent.spec.js
> Fix #254: No way to figure out if radio button values have changed

- test/e2e/specs/field-render-tests.js
> style: fix lint issues

- src/components/field-types/FileFieldComponent.vue
> fix: required field not file field not evaluated 

- CHANGELOG.md
> doc: prepare changelog for next release

- README.md
> Fix table layout in markdown

- CHANGELOG.md
- src/components/FormFieldMessages.vue
- src/components/field-types/TypedFieldComponent.vue
- src/example/number-field/DecimalExample.vue
- src/example/number-field/IntegerExample.vue
- src/example/number-field/LongExample.vue
- test/unit/specs/FormFieldMessages.spec.js
- test/unit/specs/field-types/TypedFieldComponent.spec.js
Compute min and max value based on range and input type
Fixes #267
> Replace range validator with default min and max validators

- CHANGELOG.md
- src/components/field-types/DateFieldComponent.vue
- test/unit/specs/field-types/DateFieldComponent.spec.js
> Fix 293 Null or undefined date string results in invalid parse attempt

- src/components/FormFieldMessages.vue
Fixes #295
- Code unit/integration/system tested
> fix: specify key for validation messages

- CHANGELOG.md
- README.md
- src/util/EntityToFormMapper.js
- src/util/helpers/expressionEvaluators.js
- test/unit/specs/util/helpers/expressionEvaluators.spec.js
> fix: gracefully handle evaluator errors #8470

- src/components/field-types/DateFieldComponent.vue
- test/unit/specs/field-types/DateFieldComponent.spec.js
> fix: #299 Date(time) field clear button does not clear the value

- CHANGELOG.md
> prepare release 4.0.1 ( fix clear date-date button bug) 

- test/e2e/specs/field-render-tests.js
Fix 180 
- No warnings during install
> fix 180: Use ISO time in test

- CHANGELOG.md
- Jenkinsfile
- README.md
- package.json
> [CHORE] Added auto release

- src/components/field-types/DateFieldComponent.vue
- src/example/date/DateTimeExample.vue
- test/unit/specs/field-types/DateFieldComponent.spec.js
- yarn.lock
> fix: parse input value prop to format used by flatpicker

- Jenkinsfile
- src/components/field-types/TypedFieldComponent.vue
- src/flow.types.js
- src/util/EntityToFormMapper.js
- test/e2e/nightwatch.conf.js
- test/unit/specs/field-types/TypedFieldComponent.spec.js
- test/unit/specs/util/EntityToFormMapper.spec.js
- update mapping to hyperlink
- use custom validator for hyperlink type
Closes #316
> fix: validate molgenis hyperlink type as uri instead of url

- src/components/field-types/TypedFieldComponent.vue
> fix: only show when a user actually typed invalid input

- src/components/field-types/TypedFieldComponent.vue
> fix: add namespace ui-form

- src/example/ExamplePage.vue
- src/example/compound/CompoundExample.vue
- src/main.js
Add compound example, with multiselect in compound to show/debug/test/fix add-option issue
> chore: Add compound example

- src/util/helpers/evaluator.js
- test/unit/specs/util/helpers/evaluator.spec.js
> fix: add newValue function to evaluator.js

- src/util/helpers/expressionEvaluators.js
Set correct expression type for each error type
> fix: evaluation errors is always isVisible

- README.md
> fix:release master

- package.json
- yarn.lock
> fix: fix version error due to release fail

- README.md
- package.json
> fix: trigger release after tags where cleaned

- src/components/field-types/TextAreaFieldComponent.vue
- src/components/field-types/TypedFieldComponent.vue
- src/example/max-length/MaxLengthExample.vue
- src/flow.types.js
- src/util/EntityToFormMapper.js
- [?] No warnings during install
> fix: use maxLength from attribute metadata

- src/components/Description.vue
- src/components/DescriptionUrls.vue
- src/components/field-types/CheckboxFieldComponent.vue
- src/components/field-types/CodeEditorFieldComponent.vue
- src/components/field-types/DateFieldComponent.vue
- src/components/field-types/FileFieldComponent.vue
- src/components/field-types/MultiSelectFieldComponent.vue
- src/components/field-types/RadioFieldComponent.vue
- src/components/field-types/SingleSelectFieldComponent.vue
- src/components/field-types/TextAreaFieldComponent.vue
- src/components/field-types/TypedFieldComponent.vue
- src/formDemoMockResponse.js
- test/unit/specs/Description.spec.js
- test/unit/specs/DescriptionUrls.spec.js
> feat: add automatic url's and show more text to description

- src/formDemoMockResponse.js
- src/util/EntityToFormMapper.js
- test/unit/specs/util/EntityToFormMapper.spec.js
- test/unit/specs/util/test-schemas.js
> fix: filter compound attributes too

- src/components/Description.vue
- src/formDemoMockResponse.js
- test/unit/specs/Description.spec.js
> fix: made text not required, as it can be undefined from the database

- config/index.js
> chore: add form_show_more key

- .babelrc
- build/webpack.base.conf.js
- index.html
- package.json
- src/example/validation-functions/AgeExample.vue
- src/util/helpers/expressionEvaluators.js
- test/unit/index.js
- test/unit/karma.conf.js
- test/unit/specs/util/helpers/expressionEvaluators.spec.js
- yarn.lock
> fix: use truthiness of expression result

- Jenkinsfile
- test/e2e/nightwatch.conf.js
- test/e2e/specs/field-render-tests.js
> chore: run e2e on saucelabs

- src/components/field-types/RadioFieldComponent.vue
- src/example/radio/RadioExample.vue
- src/flow.types.js
- src/util/EntityToFormMapper.js
- test/unit/specs/field-types/RadioFieldComponent.spec.js
> feat: configure if null option should be added

- src/util/helpers/expressionEvaluators.js
- test/unit/specs/util/EntityToFormMapper.spec.js
- test/unit/specs/util/helpers/expressionEvaluators.spec.js
> fix: invisible attributes are not required

- config/index.js
- index.html
- package.json
- src/components/field-types/MultiSelectFieldComponent.vue
- src/components/field-types/SingleSelectFieldComponent.vue
- src/example/multi-select/MultiSelectExample.vue
- test/e2e/specs/field-render-tests.js
- test/e2e/specs/multi-select-field-test.js
- test/e2e/specs/single-select-field-test.js
- test/unit/specs/field-types/MultiSelectFieldComponent.spec.js
- test/unit/specs/field-types/SingleSelectFieldComponent.spec.js
- yarn.lock
fixes: molgenis/molgenis-frontend#671
> fix: empty initial search value

- src/components/field-types/MultiSelectFieldComponent.vue
- test/unit/specs/field-types/MultiSelectFieldComponent.spec.js
> fix: options that are not in the intial 100, are now queried and applied

- src/components/field-types/SingleSelectFieldComponent.vue
> fix: xref now queries out of range item on start

- README.md
- src/components/DescriptionUrls.vue
- src/formDemoMockResponse.js
> feat: ability to add brakes in descriptions

- Jenkinsfile
- src/components/FormComponent.vue
- test/unit/specs/FormComponent.spec.js
> revert formComponent back to a working version 5.9.1

- README.md
> fix: force new release
