molgenis/molgenis-ui-form

package.json
Update the license string to valid license string option, this removes the warning.
License is set to same as molgenis/molgenis license.
=> Update the license string

test/unit/specs/field-types/TextFieldComponent.spec.js
Add mock function to state as parent form component is not mounted in test, this prevents errors due to calling missing parent function. This cleans up the test output
=> Fix component test error by adding mock for parent function

src/components/FormComponent.vue, src/flow.types.js, src/util/SchemaService.js, test/unit/specs/FormComponent.spec.js, test/unit/specs/util/SchemaService.spec.js
clean up console log during unit tests
The FormComponent now uses a separate service to validate its schema property
- move logic to separate module to avoid mixin business logic with render logic
- add test ( no need for mocks as it is pure js code)
- use exception instead of console log to avoid needing spy during test and having error in logs
=> fix 38 clean up console log during unit tests

package.json, test/e2e/nightwatch.conf.js, yarn.lock
- to use with safari enable remote debugging in safari web developer settings
note: at the moment one test fails using safari
=> Add e2e setup for running local firefox and safari e2e tests

test/unit/specs/field-types/MultiSelectFieldComponent.spec.js
When running yarn lint the linter warns about a missing 'state' variable, this is changed to 'fieldState'. The renaming of state to fieldState was part of a previous PR to have more structured naming.
=> code cleanup fix lint warning

test/unit/specs/FormComponent.spec.js
forgot to rename var, this results in warning during test, renaming mocks to expected formData' removes this warning
=> forgot to rename var, this results in warning during test

index.html, package.json, yarn.lock
Add shim to index.html to shim 'array.find' ( and of missing features) during dev and test.
This should fix the remote test running on ie11. During production the containing application ( molgenis should supply shims)
=> Add shim to index.html to shim 'array.find' 

src/FormDemo.vue, src/components/FormComponent.vue, test/e2e/specs/form-interaction-tests.js, test/unit/specs/FormComponent.spec.js
Change local formData from being a one time init data value to a computed value.
Updating the initialFormData property will now trigger an update to the local formData.
Although values on screen are not updated due to components having their own local copies, visible, nillable, and validation expressions are reevaluated by the data change.
=> FormComponent formData watches initialFormData property

package.json, test/e2e/nightwatch.conf.js, test/e2e/specs/field-render-tests.js, test/e2e/specs/form-interaction-tests.js, yarn.lock
Configure waits before starting actual e2e test to allow js code to run
+
Increase selection specificity on 'click the eye button' selector
=> Configure waits before starting actual e2e test to allow js code to run

README.md, config/index.js, src/components/FormFieldMessages.vue, src/components/field-types/CheckboxFieldComponent.vue, src/components/field-types/CodeEditorFieldComponent.vue, src/components/field-types/DateFieldComponent.vue, src/components/field-types/FileFieldComponent.vue, src/components/field-types/MultiSelectFieldComponent.vue, src/components/field-types/RadioFieldComponent.vue, src/components/field-types/SingleSelectFieldComponent.vue, src/components/field-types/TextAreaFieldComponent.vue, src/components/field-types/TypedFieldComponent.vue, src/formDemoMockResponse.js, src/util/EntityToFormMapper.js, test/unit/specs/field-types/CheckboxFieldComponent.spec.js, test/unit/specs/field-types/TypedFieldComponent.spec.js, test/unit/specs/util/EntityToFormMapper.spec.js, test/unit/specs/util/test-schemas.js
- number field ( can have a range object)
- range objects can have a min value, max value or both
- add custom validation messages for range ( min , max, both)
- remove type from fieldMessage properties
- add optional range property to fieldMessage component
- extend EntityMapper to include range property if set on INT of LONG type
- update readme
_ update and extend test data to include range
+
- fix flip flopping checkbox test
=> Add range validation

package.json, yarn.lock
Version 6 had a bug that emitted lots of unused events on mount, this is not a good thing in large forms.
=> bump flatpicker ( datepicker) to version 7 

config/index.js, src/components/FormFieldComponent.vue, src/components/field-types/MultiSelectFieldComponent.vue, src/components/field-types/SingleSelectFieldComponent.vue, test/unit/specs/FormFieldComponent.spec.js
Fix 'no-options' message  support to use optional i18n message for single- and multi-select
=> Fix #176 Message contains '[]' when select ( single /multi) has not options to show

package.json, src/components/field-types/DateFieldComponent.vue, test/e2e/specs/field-render-tests.js, test/unit/specs/field-types/DateFieldComponent.spec.js, yarn.lock
- Date field emits date as sting in "yyyy-mm-dd" format
- Date time emits date as ISO_8601 
Note: pretty date time format not working due to issue with vue, vue-from, vue-flatpicker interaction.
Need to create workaround (do pretty print in the description, format date_time in component) or have fix issue upstream ( vue-flatpicker altinput change, which is referring to flatpicker self)
- Clean commits - maybe rebase on master?
=> Fix/166 fix date en date-time field

src/components/FormFieldMessages.vue, src/components/field-types/CheckboxFieldComponent.vue, src/components/field-types/CodeEditorFieldComponent.vue, src/components/field-types/DateFieldComponent.vue, src/components/field-types/MultiSelectFieldComponent.vue, src/components/field-types/RadioFieldComponent.vue, src/components/field-types/SingleSelectFieldComponent.vue, src/components/field-types/TextAreaFieldComponent.vue, src/components/field-types/TypedFieldComponent.vue
- only validate after debounced value update
This solves the issue where by a form is invalid ( and maybe can not be saved) but the validation failure was not show because the field still has focus
- Updated flow typing (not relevant)
=> Trigger field validation when field becomes dirty

test/unit/specs/FormFieldComponent.spec.js
Use shallow mocking to avoid null pointer due to parent component reference
- Add expected eventBus stub
=> fix null pointer due to missing parent component

src/components/field-types/TypedFieldComponent.vue, src/example/components/ModelSettings.vue, test/e2e/specs/integer-field-test.js, test/unit/specs/field-types/TypedFieldComponent.spec.js
Fix #234 Can not clear number (int/long/decimal) fields
- Add class to example dataModel tag add hook for test code
- Add e2e test to test clearing on multiple browsers
=> [Fix 233] Set the value to null on clearing a number field

src/components/FormFieldComponent.vue, src/formDemoMockResponse.js
For required fields, the css adds an asterisk after the label.
Use escaped unicode character because the html entities do not work inside css, see https://stackoverflow.com/questions/190396/adding-html-entities-using-css-content.
Fixes #244: Asterisk for required form sometimes ends up on separate line
=> fix: Put a non-breaking space between label and asterisk

CHANGELOG.md, README.md, config/index.js, src/components/field-types/FileFieldComponent.vue, src/components/field-types/RadioFieldComponent.vue, src/example/entity/CreateEntityExample.vue, src/example/entity/UpdateEntityExample.vue, src/example/file/FileExample.vue, src/flow.types.js, src/util/EntityToFormMapper.js, test/e2e/specs/file-field-test.js, test/e2e/specs/radio-field-test.js, test/unit/specs/field-types/FileFieldComponent.spec.js, test/unit/specs/field-types/RadioFieldComponent.spec.js, test/unit/specs/util/EntityToFormMapper.spec.js
Two separate issues really:
Currently an N/A option gets added statically by the mapper when it converts metadata to form schema. The value of nillable expression does not get taken into account.
i18n value of `form_boolean_missing` is added when `attribute.nillable` is false and global mapper option `showNillableBooleanOption` is true
string `N/A` is always added when`attribute.nillable` is false
`N/A` is never added (the reported bug)
The Radio field component adds i18n value of `form_boolean_missing` when the field is currently not required. This is takes the current value of any nillableExpression into account.
The idea is that whatever the radio buttons represent, you should be able to clear them if the field is not required. The visibleExpression means that you cannot add this …
=> Fix #184: Forms behaviour on some nullable fields not as expected

CHANGELOG.md, src/util/EntityToFormMapper.js, src/util/helpers/uriGenerator.js, test/unit/specs/util/helpers/uriGenerator.spec.js
Uri generator was moved to separate file to make it easier to test. Empty mrefs selections resulted
in search for empty value, which resulted in error. Search for empty list now results in uri without
query.
Fixes #291
=> Fix #291 Cannot add new rows in molgenis for tables with mrefs

Jenkinsfile
BREAKING CHANGE: release previously unreleased change due to build issue
- Replace i18n key 'ui-form:form_not_a_valid_url' with 'ui-form:form_not_a_valid_hyperlink'
=> task: remove safari e2e test from master  build

Jenkinsfile
Disable CI e2e tests until we fix the jenkins plugin
=> fix: disable CI e2e tests
